name: Release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

env:
  PUBLISH_TARGET: testpypi

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      - name: Build package
        run: |
          python -m build
          python -m twine check dist/*

      - name: Publish to TestPyPI
        if: env.PUBLISH_TARGET == 'testpypi'
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TEST_PYPI_API_TOKEN }}
        run: |
          python -m twine upload -r testpypi dist/*

      - name: Publish to PyPI
        if: env.PUBLISH_TARGET == 'pypi'
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          python -m twine upload dist/*

  windows-binary:
    runs-on: windows-latest
    needs: build-and-publish
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install PyInstaller
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Build single-file exe
        run: |
          pyinstaller --onefile --name=bm bahasamanis_cli.py

      - name: Upload artifact to Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/bm.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
